packaging_format = 2

id = "uptime-kuma"
name = "Uptime Kuma"
description.en = "Monitoring tool like Uptime-Robot"
description.fr = "Outil de surveillance similaire à Uptime-Robot"

version = "1.23.11~ynh1"

maintainers = ["ketsapiwiq"]

[upstream]
license = "MIT"
website = "https://uptime.kuma.pet/"
demo = "https://demo.uptime.kuma.pet"
userdoc = "https://github.com/louislam/uptime-kuma/wiki"
code = "https://github.com/louislam/uptime-kuma"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "900M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "This app has a status page meant to be public and a login-protected admin interface. It should be safe to expose publicly."
    help.fr = "Cette app a une page destinée à être publique et une interface d'admin protégée par mot de passe. Elle peut être exposée publiquement sans problème."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.dist]
        url = "https://github.com/louislam/uptime-kuma/releases/download/1.23.11/dist.tar.gz"
        sha256 = "6e98ef8b7f62565ebff8cb48c3a23012b9d8044819d4f8980f99bc37bf2a468d"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "dist.tar.gz"

        [resources.sources.main]
        url = "https://github.com/louislam/uptime-kuma/archive/refs/tags/1.23.11.tar.gz"
        sha256 = "7ae1f6ab320cb22436972554fce95779e16382c00adebbc5c9be33f3298593c4"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "tarball"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.show_tile = false
    api.protected = true
