test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.540526b8571a336beb0e8402d1b24ac86bd34d2d.name = "Upgrade from 1.23.11"